# Generated by Django 5.1.6 on 2025-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("usd", "USD"), ("eur", "EUR")], max_length=3
            ),
        ),
    ]
