# Generated by Django 5.1.6 on 2025-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
