# Generated by Django 5.1.6 on 2025-02-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_item_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="product_id",
            field=models.CharField(
                default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
