# Generated by Django 5.1.6 on 2025-02-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_discount_coupon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='coupon_id',
            field=models.CharField(default=21434, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
